# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://127.0.0.1:8427
    isDefault: true
    editable: true
    jsonData:
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Bearer selectuser'

  - name: VictoriaMetrics-datasource
    type: victoriametrics-datasource
    access: proxy
    url: http://127.0.0.1:8427
    editable: true
    jsonData:
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Bearer selectuser'

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    editable: true
